### ISSUE TITLE
ft_fifo_write_byte isn't writing bytes.

### ISSUE THREAD

**Issue by page-tek** [codepainters/be_ftdi#1]
There is an error is ft_fifo_write_byte().

It should be calling ftdi_write_data() not ft_fifo_read_bytes().

Thanks for putting the example on the web.

**Comment by codepainters** [comment]
Thanks! I must have messed things up during some refactoring/cleanup. I'll recheck and update it soon.

**Comment by codepainters** [comment]
Fixed. Thanks again for spotting!
